footprints/templates/main/footprint_detail.html
the select2.css & .js are producing a 400 Bad Request when compression is attempted. Pulling these out of compress blocks until I can figure out why.
=> Fix 400 Bad Response error when viewing detail page

footprints/main/admin.py, footprints/main/forms.py, footprints/templates/search/search.html, media/css/main.css, media/geoposition/geoposition.js
adding basic interaction for prev/next, pagination
polishing up design
throwing in a few admin changes as well
=> Search Page Basics

footprints/main/admin.py, footprints/main/models.py, footprints/main/tests/test_models.py
adding id to book copy references to allow easier disambiguation
=> Admin Tweaks

footprints/main/models.py, footprints/main/tests/test_models.py, footprints/templates/main/person_detail.html, footprints/templates/main/place_detail.html, footprints/templates/main/writtenwork_detail.html, footprints/templates/search/search.html, footprints/urls.py, media/css/main.css
Adding more descriptive result information for model types: Person, Place, WrittenWork, Footprint
Removing Imprint as a searchable object
Making Detail pages more uniform
=> Search results

footprints/main/migrations/0004_auto_20150204_1502.py, footprints/main/models.py, footprints/main/search_indexes.py, footprints/main/serializers.py, footprints/main/views.py, footprints/templates/main/footprint_detail.html, footprints/urls.py, media/bootstrap3-editable/css/bootstrap-editable.css, media/bootstrap3-editable/js/bootstrap-editable-actor.js, media/css/main.css, media/js/app/editFootprint.js
Sketching out additional footprint detail functionality
note: the detail page/js is starting to bloom. I'll be refactoring this in the next few days into clearer backbone/client-side templates.
=> Footprint workspace

footprints/main/models.py, footprints/main/views.py, footprints/templates/main/footprint_list.html, footprints/templates/main/index.html, footprints/templates/search/search.html, footprints/urls.py, media/css/main.css
Using the generic Django ListView to implement a quick browse interface.
=> Footprints Browse Interface

footprints/main/admin.py, footprints/main/forms.py, footprints/main/migrations/0006_auto_20150209_1418.py, footprints/main/models.py, footprints/main/tests/__init__.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/main/tests/test_permissions.py, footprints/main/tests/test_views.py, footprints/settings_shared.py
Remove unused Name object (overly complex)  
DigitalObject factory -- FileField implementation took a few minutes to figure out  
Increasing Test Coverage
=> Model Cleanup + Test Coverage

footprints/main/forms.py, footprints/main/models.py, footprints/main/search_indexes.py, footprints/main/serializers.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/search/indexes/main/person_text.txt, media/bootstrap3-editable/js/bootstrap-editable-actor.js, media/bootstrap3-editable/js/bootstrap-editable-title.js, requirements.txt, solr/schema.xml
* Fixing autocomplete name duplication …	 3e55c83  
* Fixing autocomplete title duplication …	 5e3f424  
* Fix Person full text search ...	 4d3097e  
* Adding sort field to the SOLR index …	 5905798
=> Search & Autocomplete Tuning

footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, media/bootstrap3-editable/js/bootstrap-editable-actor.js, media/bootstrap3-editable/js/bootstrap-editable-place.js, media/bootstrap3-editable/js/bootstrap-editable-title.js, media/js/app/editFootprint.js
Further research shows XEditable already has a way to specify custom templates. (rtfm, der)
=> Refactor XEditable Templates

footprints/main/migrations/0007_auto_20150211_1240.py, footprints/main/models.py, footprints/main/serializers.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/main/viewsets.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/main/footprint_detail.html, footprints/templates/xeditable/identifier.html, footprints/urls.py, media/bootstrap3-editable/js/bootstrap-editable-identifier.js, media/js/app/editFootprint.js
* restful serializer & viewset
* xeditable custom type, template
* add/remove views
* unit testseditable-standard-identifiers
=> Editable Standardized Identifier

footprints/main/models.py, footprints/main/serializers.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/main/viewsets.py, footprints/templates/clientside/footprint_connect.html, footprints/templates/clientside/footprint_progress.html, footprints/templates/main/footprint_detail.html, footprints/templates/record/create_footprint.html, footprints/urls.py, media/css/main.css, media/js/app/footprint-detail.js
Immediately after footprint creation, offer a connect record interface.
User can choose to connect a WrittenWork, Imprint or BookCopy.
Utilizing the ajax features of select2 along with django-rest viewset filters.
=> Connect Related Records

footprints/main/models.py, footprints/main/tests/test_models.py, footprints/templates/main/footprint_list.html
* removing publisher per client's request.
=> Display Printer in Browse, Imprint Description

footprints/main/models.py, footprints/main/serializers.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/templates/main/book_description.html, footprints/templates/main/imprint_description.html, media/js/app/footprint-detail.js
* Imprint - show title, publication date & location
* Book Copy - show aggregate identifier, owners and provenance
=> Connect Record: enhance display to allow for easier disambiguation

footprints/main/views.py, footprints/templates/clientside/footprint.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/footprint_list.html, footprints/templates/main/person_detail.html, footprints/templates/main/writtenwork_detail.html, footprints/templates/xeditable/actor.html, media/js/xeditable/bootstrap-editable-actor.js
* link to written work from footprint
* rearrange actor entry form
* little polish for browse, writtenwork & person pages.
=> miscellany

Makefile, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/clientside/footprint_connect_confirm.html, media/js/app/footprint-detail.js
* required fields are marked as "editable-required"
* non-required fields can be cleared.
* fixing nit in connect confirm
* extending remove-related hack, that refactor will take place in the next day or two
=> Adding Required Field Behavior

Makefile, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/main/footprint_detail.html, media/js/app/footprint-detail.js
* Remove digital objects interface at the footprint level
* Refactor RemoveRelated into a generic remove
=> Remove Image interface & Refactoring

footprints/main/migrations/0011_auto_20150302_1039.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/clientside/footprint_connect_confirm.html, footprints/templates/main/footprint_connect.html, footprints/templates/record/create_footprint.html, footprints/templates/xeditable/actor.html, footprints/templates/xeditable/author.html, footprints/templates/xeditable/identifier.html, footprints/templates/xeditable/place.html, footprints/templates/xeditable/publisher.html, media/css/main.css, media/js/app/footprint-detail.js
* text tweaks
* swapping ? mark glyphicon for * in the Do You Know sections
=> Adding tooltips for field-level help

footprints/main/forms.py, footprints/templates/main/writtenwork_detail.html, footprints/templates/search/indexes/main/footprint_text.txt, footprints/templates/search/indexes/main/writtenwork_text.txt, footprints/templates/search/search.html, media/js/app/footprint-detail.js
* remove person & place from model types to search
* add footprint place & imprint place to footprint full text search.
* add imprint place to written work full text search.
* pull links to person/place. (pages are not complete)
* city is not a required field for place.
=> Place tuning

footprints/main/permissions.py, footprints/main/tests/test_mixins.py, footprints/main/tests/test_permissions.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/main/viewsets.py, footprints/mixins.py, footprints/settings_shared.py, footprints/templates/base.html, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/index.html, footprints/urls.py, media/css/main.css
* Browse/Search/View are available without authentication.
* All authenticated users can edit
* Tweaking navbars to reflect standard site elements.
=> Open site for public viewing

footprints/main/migrations/0013_footprint_percent_complete.py, footprints/main/migrations/0014_auto_20150505_1400.py, footprints/main/models.py, footprints/main/tests/test_models.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_list.html, media/css/main.css, media/js/jquery-circle-progress/circle-progress.js
* making percent_complete a property on Footprint
* percent_complete is updated on Footprint save
* drawing percent_complete as a circle using this little library (https://github.com/kottenator/jquery-circle-progress/)
* Adding sort by percent_complete
=> Browse percent complete

footprints/templates/main/footprint_detail.html, media/css/main.css, media/js/app/footprint-detail.js
Hide relevant divs until initial clientside render is complete.
=> Fix detail view flash

footprints/templates/xeditable/digitalobject.html, media/js/xeditable/bootstrap-editable-digitalobject.js
Uploaded files need to be < 7mb.  
Appropriate error messaging added.
=> Limit upload image size

media/js/xeditable/bootstrap-editable-digitalobject.js
* mixing jQuery & plain javascript syntax
* also hiding the error message once the user corrects the size problem by adding a new file.
=> Fix Javascript Error

footprints/main/tests/test_views.py, footprints/main/viewsets.py, media/js/app/footprint-detail.js
On the Footprint Details page, Connect Dialog  
* infinite scroll for lists of written works and imprints.  
* adding search by title capability for written works and imprints to support autocomplete.
=> select2 infinite scroll + searching

footprints/templates/record/create_footprint.html, media/css/main.css
=> Create Wizard layout tweak

footprints/main/models.py
* Resolving ManyToMany Warnings: null has no effect on ManyToManyField.
* Django 1.8 - get_query_set > get_queryset
https://docs.djangoproject.com/en/1.8/releases/1.8/#features-removed-in-1-8
=> Django 1.8 - warnings + get_query_set

footprints/main/admin.py, footprints/settings_shared.py, requirements.txt
(a little insurance against deletes)
=> Add reversion to the Footprints object

footprints/main/admin.py, footprints/main/models.py, footprints/main/tests/test_admin.py, footprints/main/tests/test_models.py, requirements.txt
* Using https://github.com/ixc/python-edtf
* Date display format w/tests
=> python-edtf integration

footprints/main/models.py
see conversation https://github.com/ccnmtl/footprints/pull/184
=> guard clause

footprints/templates/xeditable/place.html, media/bootstrap3-editable/css/bootstrap-editable.css, media/bootstrap3-editable/js/bootstrap-editable.js, media/css/main.css, media/js/xeditable/bootstrap-editable-place.js
moving the okay/cancel buttons around to allow more room for the form when required.
=> XEditable default form layout

footprints/main/serializers.py
pr integrated in 3.0.5
https://github.com/tomchristie/django-rest-framework/pull/2475
=> Remove ManyRelatedField patch

footprints/main/models.py, footprints/main/tests/test_models.py, media/js/app/footprint-detail.js
* return None if no type is specified
* add test
=> StandardizedIdentification.authority display bug

footprints/main/models.py, footprints/main/tests/test_models.py
* standalone century is now '14th century'. in range, the representation is till 1300s - 1400s.
* format millenium.
=> Format century + millenium

footprints/main/admin.py, footprints/main/migrations/0019_auto_20151204_0942.py, footprints/main/models.py, footprints/main/serializers.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/main/views.py, footprints/main/viewsets.py
dropping the format to better signify model
=> ExtendedDateFormat > ExtendedDate

footprints/main/models.py, footprints/main/tests/test_models.py
* creating custom manager
* adding a utility create method from date components
* tests
=> ExtendedDateManager

footprints/templates/main/footprint_detail.html, media/js/app/footprint-detail.js, media/js/xeditable/bootstrap-editable-actor.js, media/js/xeditable/bootstrap-editable-identifier.js, media/js/xeditable/bootstrap-editable-place.js, media/js/xeditable/bootstrap-editable-title.js
Move validation logic into the individual classes.
=> Refactor XEditable validation functions

footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html
* making behavior consistent with other complex/related objects
=> Dates: turn off editing

footprints/main/models.py, footprints/main/serializers.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/main/writtenwork_detail.html
django-rest-framework can be configured to serialize the __unicode__ function via a CharField source attribute
=> EDTF - serialize __unicode__

footprints/main/forms.py, footprints/main/views.py, media/bootstrap3-editable/css/bootstrap-editable.css, media/bootstrap3-editable/js/bootstrap-editable.js, media/css/main.css, media/js/xeditable/bootstrap-editable-edtf.js
Force valid dates for both start & end
=> date ranges: open & unknown are no longer valid

footprints/templates/xeditable/edtf.html, media/js/xeditable/bootstrap-editable-edtf.js
* jump the cursor to the next field as digits are entered.
=> EDTF: user-friendly year component entry

footprints/main/forms.py, footprints/main/models.py, footprints/main/tests/test_forms.py, footprints/main/views.py
* reject invalid dates, e.g. Feb 31
* for ranges, start date must be less than end date
* reject dates today or earlier
=> Date entry -- enhanced validation

footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_evidence.html, footprints/templates/clientside/footprint_progress.html, footprints/templates/main/footprint_connect.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/footprint_related.html, footprints/urls.py, media/css/main.css, media/js/app/footprint-detail.js
From the Footprint Detail page, provide functionality to create a footprint based on the current written work, imprint, physical copy and evidence. Leveraging the existing "Connect" client views to create this feature.
=> Feature: Add Related Footprint

footprints/templates/main/footprint_detail.html, media/js/xeditable/bootstrap-editable-place.js
* Google maps would very much like the dom element thank you
* also, don't submit the various forms on enter
=> Fix Place Selection

footprints/settings_production.py, footprints/settings_staging.py, footprints/wsgi.py, requirements.txt
=> serve static assets & uploads via S3

media/js/app/imprint-detail.js
* close the info window if clicking on an imprint or footprint that does not have a location
=> Infowindow management

Makefile
No need for it to be set up to 12.
=> reduce complexity to 11

footprints/main/models.py
extract a couple functions from ExtendedDate.fmt() to get its complexity down to 10.
=> Complexity 10

Makefile, footprints/main/models.py, footprints/main/tests/test_models.py
Get max complexity down a notch to 9
=> Complexity 9

footprints/batch/models.py, footprints/batch/tests/test_models.py, footprints/batch/tests/test_views.py, footprints/batch/urls.py, footprints/batch/views.py, footprints/settings_shared.py, footprints/templates/batch/batchjob_detail.html, media/css/main.css, media/js/app/batchjob-detail.js
* warn users if a batch record closely matches existing footprints
* allow user to delete a record from the batch job
* add view tests
=> Batch import: detect similar footprints

footprints/batch/models.py, footprints/batch/tests/factories.py, footprints/batch/tests/test_views.py, footprints/batch/urls.py, footprints/batch/views.py, footprints/main/models.py, footprints/main/tests/test_models.py, footprints/templates/batch/batchjob_detail.html, media/css/main.css, media/js/app/batchjob-detail.js, requirements.txt
* Process job UI
* Create footprints based on imported batch row data
* Hone similar_footprint functionality to augment data integrity checks and prevent duplication
* Unit tests
=> Transform BatchRows into Footprints

footprints/batch/tests/factories.py, footprints/batch/tests/test_views.py, footprints/batch/views.py, footprints/main/models.py, footprints/main/tests/test_models.py, footprints/settings_shared.py, requirements.txt
* use mock in tests to mimic Google reverse geocode operation
=> Batch Import: Reverse Geocode on Import 

footprints/templates/base.html, footprints/templates/main/index.html
=> Hide search until SOLR whitelist comes through

footprints/batch/models.py, footprints/batch/templatetags/batchrowtags.py, footprints/batch/tests/test_templatetags.py, footprints/batch/tests/test_validators.py, footprints/batch/validators.py, footprints/batch/views.py, footprints/templates/batch/batchjob_detail.html, media/js/app/batchjob-detail.js
* moving field-level validation into the BatchRow model to allow cross-field validation. seems cleaner then doing separate integrity checks
* adding validation for co-dependent fields: footprint_actor & footprint_actor_role
=> Validate Actor Role

footprints/batch/migrations/0003_auto_20160308_0921.py, footprints/batch/models.py, footprints/main/models.py, footprints/main/tests/test_models.py, footprints/templates/batch/batchjob_list.html, footprints/templates/search/indexes/main/actor_text.txt, footprints/templates/search/indexes/main/footprint_text.txt, footprints/templates/search/indexes/main/name_text.txt, footprints/templates/search/indexes/main/writtenwork_text.txt
* cache author and publisher roles
* cache standardized identifier types
* select_related for import integrity query
* tweak indexed templates to be a little faster
=> Optimization

footprints/templates/main/footprint_list.html, media/css/main.css, media/js/app/footprint-list.js
* More data > more pages > new look & feel
* Factoring javascript into its own view
=> Redesign pagination

footprints/main/search_indexes.py, footprints/settings_production.py, footprints/settings_shared.py, footprints/settings_staging.py, requirements.txt
configuration for django-transaction-hooks and celery-haystack
=> celery-haystack integration

footprints/batch/migrations/0004_batchrow_footprint.py, footprints/batch/models.py, footprints/batch/tests/test_views.py, footprints/batch/views.py, footprints/settings_shared.py, footprints/templates/batch/batchjob_detail.html
* Store the footprint created from batch row processing.
* Display the footprint link post-process for auditing.
=> Connect BatchRow to New Footprint

footprints/main/views.py, footprints/templates/main/footprint_list.html, footprints/templates/main/pagination.html, media/css/main.css
* pagination colors & placement
* underline links in informational messages.
=> Style tweaks

footprints/main/models.py, footprints/templates/main/writtenwork_description.html, media/css/main.css
=> Expand WrittenWork Description

footprints/batch/tests/test_views.py
* test_add_author failed on kodos but not other environments
=> Fix non-deterministic test

footprints/main/admin.py, footprints/templates/admin/login.html
Search footprints by creator
Add creator to Footprints list view
Search persons by name
=> Admin: search/list view

footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_list.html, media/css/main.css
* remove evidence location
* add footprint date
* add footprint location
introduce non-database sorts for footprint date and footprint location.
=> Browse: new column requirements

footprints/main/forms.py, footprints/templates/clientside/footprint.html, footprints/templates/main/writtenwork_detail.html, media/css/main.css
* footprint list items: move details back to left
* footprint list items: move map icon to the right, and show cursor on hover
* search: written works display name is "Literary Work"
=> Written Work page tweaks

footprints/main/migrations/0023_bookcopy_call_number.py, footprints/main/migrations/0024_auto_20160503_1534.py, footprints/main/models.py, footprints/main/serializers.py, footprints/templates/clientside/footprint_book.html, requirements.txt
* add to model
* provide add/edit interface
* backfill -- The book copy's call number is equal to the footprint's call number when the medium is "Owner signature/bookplate in extant copy"
=> Book Copy: call_number field

footprints/batch/views.py, footprints/main/admin.py, footprints/main/models.py, footprints/main/tests/test_models.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_list.html
* Add sort by owners
* Refactor roles approach
* searching for roles by constant names is more efficient than selecting the role explicitly.
=> Browse: Add sort by owners

footprints/main/tests/test_views.py, footprints/main/views.py
=> AddLanguageView: remove the language relationship

django.mk, footprints/batch/models.py, footprints/batch/tests/factories.py, footprints/batch/tests/test_models.py, footprints/batch/tests/test_views.py, footprints/batch/views.py, footprints/main/tests/factories.py
* validate call number
* get existing book copy based on call number
=> Batch Import: book copy call number

footprints/main/models.py, footprints/main/serializers.py, footprints/main/tests/test_models.py, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, media/css/main.css
* Book Copy: retrieve and display the most recent owner of the physical copy
* Book Copy: display information between Footprint and Literary work/imprint rather than at the end of the page.
* Footprint: move notes above evidence fields
* Footprint:  Rename Evidence Call Number to Evidence Source. Update "Do You Know" question to reflect the change.
=> Footprint Detail page - reorganization and additional field

footprints/main/admin.py, footprints/settings_shared.py, requirements.txt
django-haystack 2.5.0 works with Django 1.9 now so it appears possible to upgrade.
=> :arrow_up: Django 1.9

footprints/batch/urls.py, footprints/urls.py
convert to new style `urls.py`
=> Django 1.10 urls

.dockerignore, .gitignore, Dockerfile, README.md, docker-compose.yml, docker-run.sh, docker.mk, footprints/settings_compose.py, footprints/settings_docker.py
I'm too lazy to set up postgis on my desktop. That's been limiting my
ability to properly work on this project.
So here's a docker-compose setup that uses a postgis container so I
don't have to think about it anymore.
=> docker-compose setup

docker-compose.yml
I guess footprints doesn't actually use GIS stuff after all
=> just use plain postgres image

footprints/main/tests/test_views.py, footprints/main/views.py
Send the email from an accepted address
=> Resolve message rejected error

footprints/main/tests/test_views.py, footprints/main/views.py
=> Allow all languages to be deleted

media/js/xeditable/bootstrap-editable-edtf.js
should resolve edge case in sentry #172400213
=> Extra validation on millenium values

footprints/main/forms.py, footprints/main/tests/test_forms.py
A value error is thrown if the date is 1000, and marked as uncertain & approximate.
=> Handle invalid date exception

footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
Prepping for imprint/copy permalink feature.
* Cleanup template
* Make look/feel more consistent with the footprints detail page.
* Add "active" highlight at the book copy level.
* Remove icons
=> Written Work page: rework

footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
Use pushState/popState to record and playback navigation to Imprint/BookCopy/Footprint.
=> Written Work detail page: implement intrapage history

footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
Replace the full Bootstrap "collapse" with a simple show/hide toggle.
=> Written Work Detail: refactor layout

footprints/main/tests/test_views.py, footprints/main/views.py, footprints/urls.py
This commit creates the following:
* A view to export search results
* Tests for new view.
* A URL route to the new view.
The new view extends the existing search results view. It takes the
search's query set, picks out the needed fields, and streams the result
out to the client.
=> Add CSV export tool

footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
Sync the imprint/copy/footprint list properly when a user clicks a map icon.
* revisit spiderfier logic 
* differentiate pins via color & alpha
* add legend to top of map
=> Written Work: refactor map-centered interaction 

footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
=> Written Work page: make the work selectable

footprints/main/models.py, footprints/templates/base.html, footprints/templates/clientside/footprint_carousel.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/writtenwork_detail.html, media/css/main.css, media/js/app/imprint-detail.js
* Add a photo carousel at the imprint level if photos exist.
* refactor css class .active > .infocus as the Bootstrap carousel uses "active"
* add some better styling
=> Written Work Page: add a photo gallery at the imprint level

footprints/main/tests/test_views.py, footprints/main/views.py
This commit modifies the export view to yeild the values of the header
row on the firt call of its generator.  It also includes a test for the
header row values.
=> Add header row to export

footprints/templates/base.html, footprints/templates/main/index.html, media/css/main.css
The navbar was duplicated across base.html & index.html. Refactoring to eliminate
redundant markup.
=> Templates: navbar refactor

footprints/main/models.py, footprints/main/tests/test_models.py, footprints/main/views.py, footprints/templates/base.html, footprints/templates/main/moderation.html, footprints/templates/main/moderation_errors.html, media/css/main.css
Basic list view to display flagged footprints. @todo: sort & filter
=> Flagged footprint view

footprints/batch/models.py
=> Batch: imprint integrity, check for publication date existence

footprints/batch/models.py, footprints/batch/tests/test_views.py, footprints/batch/views.py, footprints/templates/batch/batchjob_detail.html, media/css/main.css, media/js/app/batchjob-detail.js
This PR removes some complex client-side interface updates in favor of a straight form submit.
=> Batch row update refactor

footprints/main/models.py, footprints/main/serializers.py, footprints/templates/clientside/footprint_progress.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/moderation.html
Serialize moderation flags to allow automatic ui update as instance properties change.
=> Footprint serializer: add moderation flags

footprints/main/tests/test_views.py, footprints/main/utils.py, footprints/main/views.py, footprints/templates/base.html, footprints/templates/clientside/footprint.html, footprints/templates/clientside/footprint_book.html, footprints/templates/main/footprint_detail.html
Creators can edit properties on objects they authored. This PR conditionally removes edit capabilities from the interface.
=> Creator: allow creation and editing of own footprint/copy/imprint/work

footprints/main/templatetags/moderation.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/templates/main/moderation.html
Identified by their inclusion in the Creator group
=> Moderation - flag footprints created by new contributors

footprints/templates/main/footprint_list.html, media/css/main.css
=> Browse: add footprint count

footprints/main/views.py, footprints/urls.py
SearchDispatchView: route between old browse view & new advanced search view
=> SearchDispatchView: waffle old browse view & new advanced search view

footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_advanced_search.html, footprints/templates/main/footprint_list.html, footprints/urls.py
Swap in the new, extended search for the old search. Remove the waffle.
=> Replace search

footprints/main/forms.py, footprints/main/tests/test_forms.py, footprints/main/views.py
* Consolidate the AdvancedSearchForm and SearchForm into one form.
* Use args/kwargs to complete the query. This sets the form up for more parameters.
=> Search form refactor

footprints/main/views.py, media/js/app/footprint-list.js
shortening search criteria names
=> direction > d

footprints/templates/main/footprint_advanced_search.html, media/js/app/footprint-search.js
The search behavior will be changing shortly. Copy the code so search can be changed without breaking browse. (Browse will be removed once search is fully in place.)
=> Search: duplicating footprint-list.js

footprints/main/forms.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_advanced_search.html, footprints/templates/main/pagination.html, footprints/urls.py, media/js/app/footprint-list.js, media/js/app/footprint-search.js
Previously, direction, sort_by and page were dealt with outside the form logic.
=> Search Form: extend form to include all criteria

footprints/main/views.py, media/js/app/footprint-list.js
inadvertently changed when working on the search feature
=> Footprint Browse: fix the direction arguments

footprints/main/forms.py, footprints/main/tests/test_forms.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/main/footprint_advanced_search.html
The UI and search proper respond differently depending on which action the user
selects.
=> Footprint Search: Differentiate Search from Filter from Pagination

.gitignore, footprints/batch/forms.py, footprints/batch/tests/test_forms.py, footprints/batch/tests/test_views.py
This commit validates the header row according to these values:
https://github.com/ccnmtl/footprints/wiki/Batch-Import-Format
=> Validate batch import header row.

footprints/main/forms.py
Model a "drill down" approach for actors. Checked actors are now queried as AND
rather than OR.
=> Search: tweak actor search

footprints/main/admin.py
facilitating some data integrity fixes
=> Better Place administration

footprints/main/models.py, footprints/main/tests/test_views.py, footprints/main/views.py
Long term plan is to clean up the data and add some unique constraints.
=> Place duplication - pick the first place

footprints/main/tests/test_views.py, footprints/main/views.py, footprints/settings_shared.py, footprints/templates/main/footprint_advanced_search.html, footprints/templates/main/footprint_list.html, footprints/urls.py, media/js/app/footprint-search.js
This PR moves the export feature from Browse (deprecated) to Search. Some minor refactoring work was needed around tests to isolate functionality and eliminate the need for a full Solr backend.
=> Integrate export feature with search

.eslintrc.js, .gitignore, Makefile, media/js/app/csrf-protection.js, media/js/app/footprint-detail.js, media/js/app/imprint-detail.js, media/js/app/sharing.js, media/js/xeditable/bootstrap-editable-actor.js, media/js/xeditable/bootstrap-editable-digitalobject.js, media/js/xeditable/bootstrap-editable-edtf.js, media/js/xeditable/bootstrap-editable-identifier.js, media/js/xeditable/bootstrap-editable-place.js, media/js/xeditable/bootstrap-editable-title.js, package.json
* resolving a few warnings for [object injection](https://blog.liftsecurity.io/2015/01/14/the-dangers-of-square-bracket-notation/), and ignoring a few that I don't think are an issue.
=> eslint security checks

footprints/templates/main/index.html
Adding in some missing parameters
=> Homepage Search: hook up to new search code

footprints/main/models.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/footprint_progress.html, footprints/templates/main/footprint_description.txt, footprints/urls.py
Use Django's [syndication feed framework](https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/) to add an rss feed for newly verified footprints.
=> Rss feed for newly verified footprints

footprints/main/views.py
=> RSS Feed: place narrative in title

footprints/main/forms.py, footprints/main/tests/test_forms.py
* add a little more validation around dates
=> Footprints Search: add more validation

footprints/main/models.py
When creating a place from a string, grab the first match. Some places are
duplicated due to earlier data integrity issues.
=> Place creation: tolerate duplicates

footprints/templates/admin/main/actor/change_form.html, footprints/templates/admin/main/bookcopy/change_form.html, footprints/templates/admin/main/collection/change_form.html, footprints/templates/admin/main/digitalobject/change_form.html, footprints/templates/admin/main/footprint/change_form.html, footprints/templates/admin/main/imprint/change_form.html, footprints/templates/admin/main/person/change_form.html, footprints/templates/admin/main/standardizedidentification/change_form.html, footprints/templates/admin/main/writtenwork/change_form.html
The extra forward slash in the select2 include statement is causing errors.
=> Update select2 includes

footprints/main/admin.py, footprints/main/models.py, footprints/main/tests/test_models.py
Don't blow up if the month format is invalid.
Also, tuning the admin interface a bit to make it easier to view dates.
=> Tolerate badly formatted dates

footprints/templates/search/indexes/main/footprint_text.txt, solr/schema.solr7.xml
* also stashing a Solr 7 placeholder schema.xml
=> Footprints search: add creator to the full text search

requirements.txt
The latest release is causing issues with search. Pin until we can sort out the issues.
=> Pin Haystack to < 2.7.0

footprints/main/models.py
Handle the case where multiple actors match creation criteria. @todo - review data integrity issues around Actors
=> Batch: Handle multiple actors found

requirements.txt
=> Update Requests 2.15.1 => 2.19.1

requirements.txt
Fixes build problem uncovered by jenkins
=> Add missing certifi module

footprints/templates/flatpages/default.html
Footprints flatpages are html based
=> Remove markdown dependency

requirements.txt
Needed as an s3transfer dependency
=> add futures backport

footprints/templates/base.html, footprints/templates/flatpages/default.html, footprints/templates/main/index.html, footprints/templates/main/writtenwork_detail.html
Open graph and twitter card for the following pages
- home page
- flatpages
- written work
=> Open graph and twitter card for specific pages

footprints/templates/base.html, footprints/templates/flatpages/default.html, footprints/templates/main/footprint_advanced_search.html, footprints/templates/main/footprint_detail.html, footprints/templates/main/index.html, footprints/templates/main/writtenwork_detail.html
=> Search engine optimization

.travis.yml, requirements.txt
footprints is now on celery02.
=> Remove python 3.4 support

footprints/batch/forms.py, requirements.txt
Remove special handling. Invoking the csv reader works just fine.
=> Tweak CSV file processing

footprints/main/forms.py, footprints/main/search_indexes.py, footprints/main/serializers.py, footprints/main/tests/test_forms.py, footprints/main/tests/test_views.py, footprints/main/views.py, footprints/templates/clientside/search_template.html, footprints/templates/main/map.html, footprints/urls.py, media/js/app/components/mapvue.js, media/js/app/components/searchvue.js, media/js/app/pathmapper.js, solr/schema.xml
Backing up a bit and focusing on the search for book copies. This PR simply returns the number of book copies that are found given a set of criteria. Removing some experimental code that attempted to return the search total and the paths.
Note: this also updates the solr search schema, so please coordinate with me before merging.
=> BookCopy search forms & views

footprints/main/forms.py, footprints/main/tests/test_forms.py
Resolve a Sentry error where a (bogus) Contact request came through without a subject.
=> Verify correct Contact params

footprints/templates/clientside/search_template.html, media/css/main-new.css, media/css/pathmapper-tool.css, media/js/app/components/searchvue.js
Request a check of `searchvue.js`
=> Pane slide in an out

media/css/pathmapper-tool.css
The hide/show pane button doesn't work properly on tablet size. I have to rethink how this work on tablets.
=> Initial placement for the panes in medium screen devices

footprints/pathmapper/forms.py, footprints/templates/clientside/layer_template.html, footprints/templates/clientside/select_widget_template.html, media/js/app/components/layervue.js, media/js/app/components/select-widget.js
* Allow html markup in select2 options
* Add select2 wrapper for Imprint, locations and person.
* Disable imprint field if work has not yet been selected
=> LayerVue: begin hooking up criteria fields

footprints/main/serializers.py, footprints/settings_shared.py, footprints/templates/clientside/footprint_connect_confirm.html, footprints/templates/main/footprint_connect.html, media/js/app/footprint-detail.js
Dealing with several breaking changes around initial selection, values and ajax integration
=> Update code to support Select2, v4

footprints/main/search_indexes.py, footprints/main/tests/test_views.py, footprints/main/tests/test_viewsets.py, footprints/main/viewsets.py, footprints/pathmapper/forms.py, footprints/pathmapper/tests/test_forms.py, footprints/templates/clientside/layer_template.html, footprints/urls.py, media/css/pathmapper-tool.css, media/js/app/components/layervue.js, media/js/app/components/select-widget.js, media/js/app/footprint-detail.js
* Accept and search for imprint and footprint place ids
* refactor viewset tests into a separate file
=> Pathmapper: add imprint and footprint location to search

footprints/templates/main/footprint_detail.html, media/js/app/csrf-protection.js
The cookies are now secure and can't be used by script.
=> Update clientside csrf approach

footprints/templates/base.html
This should act to cachebust against existing browsers.
=> Compress csrf protection script

footprints/main/tests/test_utils.py, footprints/main/utils.py
Utility code ripped off from Stack Overflow to convert javascript variable names to Python variable names and back again.
=> Snakes & Camels

footprints/templates/clientside/layer_template.html, media/js/app/components/layervue.js
=> Pathmapper: display date entry string

footprints/main/models.py, footprints/main/search_indexes.py, footprints/main/smoke.py, footprints/main/tests/test_search_indexes.py, footprints/main/tests/test_views.py, footprints/main/tests/test_viewsets.py, footprints/main/viewsets.py, footprints/pathmapper/forms.py, solr/schema.solr7.xml, solr/schema.xml
Switch to more robust Solr search backend rather than the more vanilla Django search. This enables date range queries for footprints and imprints.
=> Point Imprint & WrittenWork API endpoints to Solr

footprints/main/search_indexes.py, footprints/main/tests/test_search_indexes.py, footprints/main/views.py, footprints/main/viewsets.py, footprints/pathmapper/forms.py, footprints/templates/clientside/layer_template.html, footprints/templates/main/footprint_advanced_search.html, media/js/app/components/select-widget.js, solr/schema.solr7.xml, solr/schema.xml
_Note: this PR (and the next) will require the solr schema to be redeployed and the index rebuilt. Please leave this until Monday._
* Add index elements for Imprint and Footprint to cover the place searches -- make these consistent as `imprint_location` and `footprint_location` across all the indicies.
* Use location facet fields to pull out relevant fields
* Add a switch to indicate whether searching for Imprint or Footprint locations
* Integrate all the other search criteria into the search via a form
* Unit tests coming in the next PR.
=> Pathmapper: handle location searches

footprints/main/serializers.py, footprints/pathmapper/tests/test_views.py, footprints/pathmapper/views.py, footprints/templates/clientside/pathmapper_table.html, footprints/urls.py, media/css/main-new.css, media/js/app/components/tableVue.js
Coloring slightly outside the lines here by:
* Forcing the ListView into using POST to return data. This request is idempotent, but the input is a fairly complex possibly large array. Using POST here makes things much easier.
* Forcing the ListView to return json via the RestFramework serializer. This data is used by a clientside component to dynamically render the data. The ListView does a lovely job with pagination, which I want to leverage.
=> Pathmapper: Populate the table

footprints/main/models.py, footprints/main/serializers.py, footprints/pathmapper/views.py, requirements.txt
More data will likely be needed, but paring it down to the minimum set to begin
=> Pathmapper: minimize the serialized data

footprints/templates/clientside/pathmapper_map.html, footprints/templates/pathmapper/map.html, media/js/app/components/layermapvue.js, media/js/app/components/mapvue.js
Move the mapping functionality into the targeted layer vue to allow finer control over changes.
=> Pathmapper: map layer vue

footprints/pathmapper/views.py
Addresses sentry error FOOTPRINTS-1W.
=> Add case for when stats[key] is None

footprints/templates/design/pathmappervision.html, footprints/urls.py
* `/pathmapper` now goes to pathmapper
* `/pathmapper/vision` now goes to the pathmapper wireframes
=> Pathmapper: a little url refactoring

footprints/templates/clientside/layer_list_template.html, footprints/templates/clientside/pathmapper_location.html, footprints/templates/clientside/pathmapper_map.html, footprints/templates/pathmapper/map.html, media/css/pathmapper-tool.css, media/js/app/common.js, media/js/app/components/layerlistvue.js, media/js/app/components/layermapvue.js, media/js/app/components/locationvue.js, media/js/app/components/mapvue.js, media/js/app/pathmapper.js
Clicking on a map marker will now produce a "location detail" view to describe the point of interest.
=> Pathmapper: introducing the location detail vue

footprints/templates/clientside/layer_form_template.html, footprints/templates/clientside/pathmapper_location.html, footprints/templates/clientside/pathmapper_map.html, media/js/app/components/layerformvue.js, media/js/app/components/layerlistvue.js, media/js/app/components/layermapvue.js, media/js/app/components/mapvue.js
Ideally, there should be just one marker per unique latlng. This refactoring centralizes the marker creation into the MapVue.
=> Pathmapper: Centralize marker creation

footprints/local_settings.py.example, footprints/main/views.py, footprints/templates/base.html, footprints/templates/xeditable/place.html, media/css/main.css, media/js/xeditable/bootstrap-editable-place.js
Switch from Google Places API to the Geonames API.
=> Geonames API integration

footprints/main/migrations/0042_auto_20200421_1313.py
Per doc here: https://docs.djangoproject.com/en/3.0/howto/writing-migrations/#non-atomic-migrations
=> Make the CanonicalPlace migration non-atomic

footprints/main/admin.py
Adjusting the admin console to provide a better view into the existing objects.
=> Tweak Place and CanonicalPlace admin

footprints/main/admin.py, footprints/settings_shared.py, footprints/urls.py, requirements.txt
To allow record merging through the admin console. @hmchesner 😺
=> Enable django-adminactions

footprints/main/management/commands/consolidate_places.py, footprints/main/tests/test_consolidate_places.py
Management command to merge duplicate places into a single place, transferring over dependencies as it goes.
=> Consolidate Places

footprints/batch/models.py, footprints/batch/tests/test_validators.py, footprints/batch/tests/test_views.py, footprints/batch/validators.py, footprints/batch/views.py, footprints/main/tests/test_utils.py, footprints/main/utils.py
Replaces latlng & Google reverse geocoding operations
=> Update batch processing to accept geoname ids

footprints/main/viewsets.py
This is in the CanonicalPlace object now
=> Fix canonical_name reference

footprints/templates/clientside/pathmapper_table.html, media/css/pathmapper-tool.css, media/js/app/components/tableVue.js
=> Pathmapper: respect layer visibility in table view

footprints/main/viewsets.py, footprints/pathmapper/tests/test_views.py
=> PlaceViewSet: fix attribute reference

footprints/templates/clientside/layer_form_template.html, media/css/pathmapper-tool.css
=> Made buttons for save/create/cancel layer float at the bottom

media/js/app/components/mapvue.js
This PR scales the place markers based on the percent of events that initiate, pass through or terminate. Place markers have a minimum radius of 5. Also adding an outline to the markers.
=> Pathmapper: first pass at density circles

footprints/templates/clientside/layer_form_template.html, media/css/pathmapper-tool.css, media/js/app/components/layerformvue.js
=> Year dynamic feedback notification

footprints/templates/clientside/layer_list_template.html, footprints/templates/clientside/pathmapper_timeline.html, media/css/pathmapper-tool.css, media/js/app/components/layerlistvue.js, media/js/app/components/timelineVue.js
For desktop screen size only. Still working on responsive displays.
=> Button in layers pane to launch Timeline

footprints/templates/clientside/layer_list_template.html, footprints/templates/clientside/pathmapper_timeline.html, media/css/pathmapper-tool.css, media/js/app/components/layerlistvue.js, media/js/app/components/timelineVue.js
Timeline responsive display for table (MD) screens
=> Timeline tablet screen

footprints/templates/clientside/layer_form_template.html, footprints/templates/clientside/layer_list_template.html, media/css/pathmapper-tool.css, media/js/app/components/layerformvue.js
For now, I'm pushing this. I think I've address a lot of different kind of permutations of criteria selection, but I have seen a few that I'm not sure how to solve. They are not show stoppers.
=> Contextual display of criteria for layer form and listing

footprints/templates/clientside/layer_form_template.html, footprints/templates/clientside/layer_list_template.html, footprints/templates/clientside/pathmapper_timeline.html, media/js/app/components/layerformvue.js, media/js/app/components/timelineVue.js
=> Highchart timeline design styling, and other small changes to narrative

requirements.txt
=> Add missing django-cacheds3storage

footprints/main/search_indexes.py
Tune solr index with prefetch_related, select_related...This doesn't gain much, but a little something is better than nothing.
=> Optimize Solr index

footprints/main/admin.py
* Add WrittenWork search by title
* Add Actor search by alias and person name, and filter by type
* Add StandardizedIdentification search
* Add BookCopy search by imprint title
=> Enable admin searching, filtering and sorting options

footprints/main/management/commands/update_imprints.py, footprints/main/models.py, footprints/main/tests/factories.py, footprints/main/tests/test_models.py, footprints/main/tests/test_update_imprints.py
Print out created and existing/updated rows. Fix some bugs along the way
=> BHB ingest: add a log format

footprints/main/management/commands/update_imprints.py
(so Solr doesn't get really overwhelmed)
=> BHB ingest: pause between rows

footprints/main/utils.py
The returned json may not have all the fields.
=> Update geonames format code to be more tolerant

footprints/main/views.py
Clean the sort & direction query params before passing through to Solr.
=> Search query params: add some checks

footprints/templates/main/footprint_detail.html
The type change from queryset to list kaboshed the display.
=> Fix bug where related footprints blurb went missing

footprints/settings_shared.py, footprints/templates/drf_spectacular/swagger_ui.html, footprints/urls.py, requirements.txt
Using drf-spectacular to display a more detailed window into the Footprints rest API. Authentication is required.
=> Add DRF schema view

footprints/pathmapper/tests/test_views.py, footprints/pathmapper/views.py, media/js/app/pathmapper.js
* Remove narrative
* Add id and totalCopies
* Only share visible layers
=> Update shareUrl export and import

footprints/settings_staging.py
Experiment complete, this can go back to normal now.
=> Revert "Cloudfront configuration for staging"

footprints/main/models.py, footprints/main/serializers.py, footprints/templates/clientside/pathmapper_location.html, media/js/app/components/locationvue.js
In the location detail view:
* Fix issues with book copy count
* Display footprints more clearly under the Book Copy
* Display a longer description if the footprint does not have a narrative
=> Pathmapper: Fix issues with location view

footprints/main/models.py, footprints/main/search_indexes.py, footprints/main/serializers.py, footprints/main/tests/test_models.py, media/js/app/components/layermapvue.js, media/js/app/components/locationvue.js, solr/footprints/conf/managed-schema
Note: Please confirm this PR is ready to go. I'll merge as a Solr configuration change is required, then an `update_index`
=> Pathmapper: Add terminal footprint logic

requirements.txt
I am composing a bug report to the maintainer.
=> The latest adminactions has a bug in merge.

footprints/templates/admin/login.html, footprints/templates/registration/login.html, media/css/main.css
* Remove local login for admin in production situations
* Make the username/password boxes smaller for the front page login
=> Update login pages

footprints/main/tests/test_views.py, requirements.txt
File upload is working properly, but the permissions are not being set correctly
=> Downgrade django-s3sign

footprints/templates/registration/registration_form.html
=> Fix admin_static

requirements.txt
Reverts ccnmtl/footprints#2658
=> Revert "Bump django-adminactions from 1.15 to 2.0.0"

requirements.txt
Reverts ccnmtl/footprints#2773
=> Revert "⬆️ Bump billiard from 3.6.4.0 to 4.1.0"

requirements.txt
Reverts ccnmtl/footprints#2877
=> Revert "Bump django-adminactions from 1.15 to 2.1.0"

footprints/templates/registration/login.html, footprints/templates/registration/registration_complete.html, footprints/templates/registration/registration_form.html
* Added registration link to the login page
* Added Terms and Condition links to registration and registration-complete pages
* Modified error messages in registration page to make it sound more human
=> Footprints 573 registration loginpage

requirements.txt
Reverts ccnmtl/footprints#2990
=> Revert "Revert "Bump sentry-sdk from 1.32.0 to 1.33.1""

footprints/settings_shared.py
Reverts ccnmtl/footprints#3005
=> Revert "route to https"

footprints/settings_shared.py
Reverts ccnmtl/footprints#3006
=> Revert "Revert "route to https""

requirements.txt
=> Add packaging for django-haystack

footprints/settings_production.py, footprints/settings_staging.py
Just enabling sentry manually here until the new release of ctlsettings.
=> Enable sentry

footprints/batch/views.py
Reverts ccnmtl/footprints#3224
=> Revert "adding this here just to troubleshoot"

footprints/main/templatetags/moderation.py, footprints/main/tests/test_models.py
The Moderation View (`/moderate`) has slowed considerably as the number of qualifying footprints has increased. The root cause was the `flag_creator` function which queried for membership in the "Creator" group for every footprint.
This PR optimizes the main query with an annotation to determine group membership. Tests updated.
With my current data set of 4,192 footprints:
Previous: 4,198 queries with an overall view render time of 10,320ms.
Now: 7 queries with an overall view render time of 1738ms.
See screenshots below.
p.s. Hi all! :wave:
Previous
Now
=> Optimize query for Moderate Footprints view

requirements.txt
* https://docs.celeryq.dev/en/latest/history/whatsnew-5.5.html
* https://docs.celeryq.dev/projects/kombu/en/stable/changelog.html
=> Update to Celery 5.5.3 and related packages
