ccnmtl/footprints

footprints/main/models.py
footprints/main/serializers.py
footprints/main/tests/test_views.py
footprints/main/views.py
footprints/main/viewsets.py
footprints/templates/clientside/footprint.html
footprints/templates/clientside/footprint_book.html
footprints/templates/clientside/footprint_progress.html
footprints/templates/main/footprint_detail.html
footprints/templates/xeditable/actor.html
footprints/templates/xeditable/author.html
footprints/templates/xeditable/place.html
footprints/templates/xeditable/publisher.html
footprints/urls.py
media/bootstrap3-editable/js/bootstrap-editable-actor.js
media/bootstrap3-editable/js/bootstrap-editable-place.js
media/bootstrap3-editable/js/bootstrap-editable.js
media/css/main.css
media/js/app/editFootprint.js

Refactoring clientside display into a better MVC model, with the classic "model change"=="render view" setup. The code had reached a point where the ad hoc rendering was beginning to get messy. This approach will also let me very quickly put up the Person, Written Work and Place detail pages. 
The add/remove related object views were also refactored to be more generic. Both views could be made generic. This was a good first step.

Refactor clientside render

---

footprints/main/migrations/0018_auto_20151119_1259.py
footprints/main/tests/test_models.py

* Model changes in this [PR](https://github.com/ccnmtl/footprints/pull/153) required a makemigration.
* Once this migration was complete (or faked!?), the unit tests began generating a segmentation fault both in my local dev env and on travis: https://travis-ci.org/ccnmtl/footprints/builds/92130217. I debugged the issue down to a very basic reproducible test (no factories, etc.) where a ManyToMany object is set. The segmentation fault then occurs during the test data rollback. In googling, I then found this ticket: https://code.djangoproject.com/ticket/24080, which seems related.
For the moment, I've hacked it by commenting out a few test lines. This is clearly a band-aid, the segmentation fault is likely non-deterministic and will show up again as tests are added/changed. I have some …

Missing Migrations + Segmentation Fault Agita

---

footprints/main/serializers.py
footprints/main/tests/test_views.py
footprints/main/views.py
footprints/settings_shared.py
footprints/templates/base.html
footprints/templates/clientside/footprint.html
footprints/templates/clientside/footprint_book.html
footprints/templates/main/footprint_detail.html
footprints/urls.py
media/bootstrap3-editable/js/bootstrap-editable.js
media/js/app/csrf-protection.js
media/js/app/footprint-detail.js

Resolving issues related to django-rest-framework 3.3.0 [full deprecation of X-HTTP-Method-Override](http://www.django-rest-framework.org/topics/3.3-announcement/). Footprints used the method override to ease integration between XEditable, django-rest-framework, and handle csrf authentication flows. The deprecation broke all model updates via XEditable, which to my chagrin, was not caught by any unit tests. Here's the fix:
* Remove X-HTTP-Method-Override
* Append a csrf cookie to all ajax calls. Remove csrftoken from individual XEditable calls.
* Update model serializers to correctly characterize ManyToMany relationships as read only. Independent views take care of adding & removing nested list relationships.
* Replace hacky Footprint & Imprint language update method override in favor of …

Fix xeditable updates

---

media/js/app/footprint-detail.js

straight api functions do not return 'success'

Refresh tweak: check for existence of success

---

media/bootstrap3-editable/css/bootstrap-editable.css
media/css/main.css
media/js/xeditable/bootstrap-editable-edtf.js

* hide the html5 type=number spinners
* allow the delete key to be processed on keypress
* fix a z-index issue with the confirmation buttons

Resolve Firefox date ui bugs

---

media/js/xeditable/bootstrap-editable-digitalobject.js

This [PR](https://github.com/ccnmtl/footprints/pull/198) changed csrf handling to require the X-CSRFToken header. plUpload sets up its request manually, and also needs the CSRF header.

Add CSRF Header to Digital Object Upload

---

footprints/templates/base.html

(still relying on a non-secure resource for the timemapper demos)

Pull bootstrap from the cdn until Footprints is fully SSL

---

footprints/templates/main/footprint_detail.html

The static values were moved outside the model in this [PR](https://github.com/ccnmtl/footprints/pull/270). Update the template reference.

Update MEDIUM_CHOICES reference

---

footprints/settings_shared.py
requirements.txt

Afaict, it's not being used anywhere. Meanwhile `django-tagging` is
super obsolete and unmaintained. It currently does not support 1.7+
style migrations, so you can't bootstrap an empty database with it in
place (ie, `createdb footprints; ./manage.py migrate` fails with errors
about missing content types).

remove django-tagging

---

footprints/main/tasks.py
footprints/main/views.py
footprints/settings_shared.py
footprints/urls.py
requirements.txt

This adds the required libraries for celery and sets up a demo task plus
a view to test it.
The broker settings for staging/prod have been set in
`local_settings.py` and salted out to the servers and the required
rabbitmq vhosts set up.
The only part missing is that there isn't a celery worker running
anywhere yet, but of course, the libraries and such added here need to
be in the code before that can happen.
If this is merged and deployed to staging you ought to be able to test
by:
* log into the staging server and manually start up a worker
```
cd /var/www/footprints/footprints/; ./manage.py celeryd \
--settings=footprints.settings_staging
```
* then just hit
https://footprints.staging.ccnmtl.columbia.edu/celerytest/
And you should see it print in the worker console/logs.
Same thing for …

Celery setup. PMT #105639

---

footprints/templates/impersonate/search_users.html

to eliminate compress's complaint `impersonate/list_users.html: 'url' is not a valid tag or filter in tag library 'future'`

remove load from future tag from impersonate template

---

footprints/templates/batch/batchjob_detail.html

* The footprint could have been deleted
* Resolves sentry group error #1081.

Verify batch/footprint relation exists

---

footprints/settings_production.py
footprints/settings_staging.py
requirements.txt

according to: https://django-transaction-hooks.readthedocs.io/en/latest/
> `django-transaction-hooks` has been merged into Django 1.9 and is now
>  a built-in feature, so this third-party library should not be used
>  with Django 1.9+.

remove django-transaction-hooks

---

footprints/main/tests/test_views.py
footprints/main/views.py

Only accept valid sort_by values, otherwise default to the default value. Resolves sentry #167554703.

Restrict sort_by parameters

---

.gitignore
footprints/main/templatetags/detailtags.py
footprints/templates/clientside/footprint.html
footprints/templates/clientside/footprint_progress.html
footprints/templates/clientside/footprint_recordkeeping.html
footprints/templates/main/footprint_detail.html
media/css/main.css
media/js/app/footprint-detail.js

* On the detail page, add a list of related footprints for the given book copy as a right-hand sidebar.
* Move the created/modified info to the end of the page
* Move the "View All" link to the right-hand sidebar and give it a bit more text.

Footprint Detail Page: Add list of related footprints

---

footprints/templates/main/footprint_list.html

This PR creates a button that will be used to export a CSV file of search results.

Add export button to /browse/footprints/ page

---

footprints/main/views.py
footprints/templates/main/writtenwork_detail.html
footprints/urls.py
media/js/app/imprint-detail.js

The written work detail page can now reconstitute state for a selected imprint, copy or footprint.

WrittenWorkDetail: handle extended urls

---

footprints/templates/main/footprint_list.html
media/js/app/footprint-list.js

This commit adds a button to the footprint_list template to export
search results.  It also adds javascript initiate the HTTP request to
download the CSV file.

Add button for new export feature.

---

footprints/main/views.py
footprints/templates/main/footprint_list.html

This commit moves the 'Export' button from the input-group div to the div
containing the page.  This was done to make the export functionality
visually distinct from the search functionality.

Move 'Export' button.  Remove extraneous comment.

---

footprints/main/admin.py
footprints/main/serializers.py
footprints/main/tests/test_views.py
footprints/main/views.py
footprints/templates/base.html
footprints/templates/clientside/footprint_progress.html
footprints/templates/main/footprint_detail.html
footprints/urls.py
media/css/main.css

* Indicate the current Footprint's state: verified, unverified w/errors (flagged), unverified without errors (ready to verify)
* Add utility to allow moderator to verify a footprint.

Footprint Detail: add moderation utilities

---

footprints/batch/tests/test_views.py
footprints/batch/views.py
footprints/main/context_processors.py
footprints/main/tests/factories.py
footprints/main/tests/test_views.py
footprints/main/views.py
footprints/mixins.py
footprints/settings_shared.py
footprints/templates/base.html
footprints/templates/main/footprint_detail.html

* Remove 'staff' requirement for moderation and batch import
* Require `batch.*` permission for batch views
* implemented via BatchAccessMixin
* Require `main.can_moderate` for moderation views
* implemented via ModerationAccessMixin
* Update the tests to easily construct a user with the needed permissions
* Add a context processor to add in permission levels. Used for navbar construction.

Add SuperModerator role

---

footprints/templates/main/footprint_list.html

This commit has jQuery select a class that is larger in scope.  This
permits the export button to work outside the classes used for
filtering/searching.

Adjust jQuery context

---

footprints/main/search_indexes.py
footprints/main/views.py
solr/schema.xml

* Add a set of Footprint-only sort fields. 
* Redefine base text type to employ minimal tokenization and filtering which interferes with sorts.

Footprint Search Index: add sort fields

---

footprints/main/tests/test_models.py
footprints/main/tests/test_views.py

The Footprints unit tests began experiencing a segmentation fault [when newpostgis-related code. was added](https://github.com/ccnmtl/footprints/tree/more-postgis)
A complex and heavy usage of the sqlite3 savepoint logic seems to be in play. [1](http://www.sqlite.org/src/tktview?name=7f7f8026ed), [2](https://code.djangoproject.com/ticket/24080)
Reducing the amount of test setup required appears to alleviate the problem, likely just in the short-term. Fixes on the Django 1.11 version may be the ultimate answer.

main: reduce test setup

---

Dockerfile
docker-compose.yml

This should be easier than setting up a full PostGIS instance locally for development.
This pull request to the base image will need to be merged and pushed first before it will build: https://github.com/ccnmtl/docker/pull/4

postgis setup for docker-compose

---

footprints/main/migrations/0001_initial.py
footprints/main/migrations/0003_auto_20150202_1459.py
requirements.txt

This required the not-so-best-practice of modifying past migrations that referenced the django-geoposition library. Luckily, the field is based on CharField anyway, so it is a fairly innocuous operation.
For a long discussion on trying to remove a field from migrations, see this from the Django project: [Fields referenced in migrations cannot be (re)moved, even if migrations have been squashed](
https://code.djangoproject.com/ticket/23861)

Remove django-geoposition from requirements

---

footprints/main/models.py
footprints/main/tests/test_models.py

Code against the corner-case where date elements are not passed to the server.
I'm not able to reproduce this issue locally, but Sentry shows that,
on occasion, the day1 field goes missing.

ExtendedDate.from_dict - use .get to access elements

---

footprints/main/tests/test_views.py

* Resolve test warning in SearchIndexTest.test_format_sort_by. `RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.` The test case needed to pass the function a unicode string.
* Fix incorrect indent for ExportFootprintSearchTest.test_get, and then fix the test. test_get is just a quick end-to-end test.

Test tweaks

---

footprints/main/models.py
footprints/main/tests/test_models.py

Footprint verified_modified_at: set using timezone aware syntax

---

footprints/batch/models.py
footprints/batch/tests/test_models.py

Remove checks around imprint title, publication date & location

Batch imprint integrity: only require written work title match

---

footprints/main/models.py
footprints/main/search_indexes.py
footprints/main/tests/test_models.py

Tweaking the way the Footprint end_date and Imprint publication_end_date are specified to the SOLR search engine. In general, we want to make sure the end date is at the maximum end of a given range.
For example:
* An ExtendedDateTime of 1700 should specify a range of 1700-01-01 to 1700-12-31.
* An ExtendedDateTime of 1700 - present should specify a range of 1700-01-01 with an empty end date.
* An ExtendedDateTime of 1700 - 18xx should specify  a range of 1700-01-01 to 1899-12-31.
Previously, the end date was sometimes incorrectly specified as the start date or the earliest end date.

Imprint & Footprint End Dates: Return max for a given range

---

footprints/main/forms.py
footprints/main/search_indexes.py
solr/schema.solr7.xml
solr/schema.xml

This PR adds an advanced search syntax `has:image` to the Footprints search. 
Update: this can now be merged. solr configuration has been modified.

Add indexed field: has_image

---

requirements.txt

3.3.0 is for Python3 only, and Footprints is not over yet.

Downgrade django-celery

---

footprints/batch/tests/test_views.py

These failed in local dev environments, but managed to succeed through .travis, I believe because the ids were valid.

Fix Batch tests

---

footprints/main/models.py
footprints/main/search_indexes.py
footprints/main/tests/test_models.py
footprints/main/tests/test_search_indexes.py
footprints/templates/base.html
footprints/templates/search/indexes/main/bookcopy_text.txt
footprints/templates/search/search.html
solr/schema.xml

The Footprints Pathmapper visualization requires a search for book copies rather than footprints. To support this requirement, this PR adds a BookCopy object to the Solr index, allowing faster, faceted and aggregated search interfaces.
Note: This update will require deploying a new schema.xml out to the Solr instance. Please coordinate with me before merging this PR.

Add BookCopy search index

---

footprints/main/models.py
footprints/main/views.py

Reacting to the WrittenWork Actor m2m_changed signal has proved to be heavy and slow. Move the update_index trigger into the actual Add/Remove views to speed things up when batches are processed.

Remove m2mchanged at the WrittenWork level

---

footprints/main/models.py
footprints/main/serializers.py
footprints/main/tests/test_models.py
media/js/app/components/select-widget.js

Scanning a list of traditional Place display names `city, country` was proving difficult. Swap out for a `country: city` format.

Pathmapper: add Place search_title

---

.travis.yml
Makefile
footprints/main/migrations/0001_initial.py
footprints/main/migrations/0019_auto_20151204_0942.py
footprints/settings_shared.py
footprints/settings_travis.py

This PR removes the problematic table rename migration that crashes sqlite3 and adds configuration to keep Postgres testing on Travis and Sqlite3 testing on our CI server.
The sqlite3 rename issue seem to be related to this issue: https://code.djangoproject.com/ticket/29182#no1. Note that it is inherently evil to rewrite a migration...however, the migration happened years ago and I believe it will have no impact on production.
Though this fix resolves the build locally and on the CI server, Travis now reports a segmentation fault when running the unit tests. (A segfault is also a known issue with sqlite3 :memory: databases with lots of tests. Example: https://github.com/pytest-dev/pytest-django/issues/409). In order to get things moving, I'm leaving Travis to test on postgres.

Configure postgres testing for Travis CI only

---

.eslintrc.js
footprints/main/serializers.py
footprints/pathmapper/tests/test_views.py
footprints/pathmapper/views.py
footprints/urls.py
media/js/app/common.js
media/js/app/components/mapvue.js
media/js/app/components/tableVue.js
media/js/app/utils.js

This PR adds:
* PathmapperRouteView that given layer criteria, retrieves book copies and returns the serialized data for associated imprint and footprints in a paginated response. (Going forward, the serializer might be optimized to simply return the list of places that will be mapped.)
* Clientside MapVue that requests the route data. An asynchronous queue is used to tee up requests, with the hope that this approach will be reasonably efficient. Still to do -- add "next page" requests as the initial page data is retrieved, and put the route on the map.

Pathmapper: add route view

---

footprints/main/utils.py
footprints/pathmapper/tests/test_views.py
footprints/pathmapper/views.py
footprints/templates/base-new.html
footprints/templates/clientside/layer_form_template.html
footprints/templates/pathmapper/map.html
footprints/urls.py
media/js/app/components/layerformvue.js
media/js/app/components/layerlistvue.js
media/js/app/pathmapper.js
media/js/app/utils.js
requirements.txt

On the client, a share url is constructed by compressing the the array of layers into a GET query parameter string. (Possible todo: retrieve a `tinyurl` for the long querystring.)
On the server, a valid share url is rehydrated into a layer array and placed in the view context. The client checks for valid layers in the view context and reads in the data if it exists.

Pathmapper: Read / Write Share Url

---

footprints/main/serializers.py
footprints/pathmapper/forms.py
footprints/pathmapper/views.py
footprints/templates/clientside/pathmapper_table.html
media/css/pathmapper-tool.css
media/js/app/components/tableVue.js
media/js/app/utils.js

This PR leverages the Haystack SearchQuerySet to provide a reasonable default sort order for the set of footprints that are displayed in the pathmapper table. A new serializers also minimizes the json payload, returning the exact data needed to render the view.

Pathmapper Table: rethink data retrieval

---

footprints/main/models.py
footprints/main/tests/factories.py
footprints/main/tests/test_views.py
footprints/main/views.py
footprints/templates/xeditable/place.html
media/js/xeditable/bootstrap-editable-place.js

The geoname id will become (in essence) the primary key for the CanonicalPlace object. The client will now send up the id after a result has been selected.
@todo - A batch job will be constructed to retroactively populate the geoname id for existing CanonicalPlaces and hopefully clear up the duplication there.

Add Place: send up the geoname id

---

footprints/main/management/commands/consolidate_canonical_places.py
footprints/main/tests/test_consolidate_canonical_places.py

Iterate CanonicalPlace instances and identify matches based on name and proximity.

Remove CanonicalPlace duplicates

---

footprints/main/admin.py
footprints/main/tests/factories.py
footprints/main/tests/test_views.py
footprints/main/views.py

CanonicalPlaces that existed without a geoname_id could error due to incorrect get_or_create signature. Added additional tests to uncover the bug.

Fix CanonicalPlace creation bug

---

footprints/main/management/commands/populate_geoname_id.py

This job will backfill existing CanonicalPlaces with a matching Geoname ID based on the stored latitude and longitude.
The job completes 100 places in a go -- there are hard limits on the Geoname API and I want to be respectful. If a rate limit is hit, the job exits gracefully.
Duplicates are simply ignored for the purposes of this job. We're running through automated cleanup jobs, but eventually, we'll have to do some cleanup manually.

Populate Geoname ID for existing CanonicalPlaces

---

footprints/pathmapper/forms.py
footprints/pathmapper/tests/test_forms.py

The ranged variable comes in as a regular boolean, not a string.

Pathmapper: Fix the range indicator

---

footprints/main/serializers.py
media/js/app/components/layermapvue.js

* Add CanonicalPlace serializers
* Use this as the primary key in mapping places
Note: I'm choosing to leave the PlaceSerializer fields in place for the moment. Those will need to be factored out of other areas in the application.

Pathmapper: switch to using CanonicalPlace

---

footprints/pathmapper/views.py
footprints/templates/clientside/layer_form_template.html
footprints/templates/clientside/layer_list_template.html
media/js/app/components/layerformvue.js

This PR clarifies the date validation and explanatory text around the pathmapper publication and footprint date entry. This is a complicated little bit of UI, but here are the basics.
1. As a user selects criteria within the Pathmapper form, the line above the date range inputs displays the bounds of the resulting data set. In this case, the user has searched for the literary work "Abudarham" resulting in 29 book copies that were published between 1489 to 1726.
2. The line below the date range inputs offer direction on what the user has entered. In this example, the user has started to a type a year and is instructed that the start year must be between 1000 - 2020. Many permutations are handled here as the date range inputs handle a single year, a start year with an open end year, and an …

Pathmapper: Date validation and explanatory text

---

footprints/main/search_indexes.py
footprints/main/tests/test_search_indexes.py
footprints/main/viewsets.py
footprints/pathmapper/forms.py
footprints/pathmapper/tests/test_forms.py
footprints/templates/search/indexes/main/footprint_text.txt
footprints/templates/search/indexes/main/writtenwork_text.txt
media/js/app/components/select-widget.js

* Update the Solr index to use CanonicalPlace for the Footprint location and Imprint location.
* Pathmapper now works with the CanonicalPlace id rather than attempting matches against the title.
Important: This change will require a full Solr index rebuild. Please review & approve the PR, but wait to merge.

Change Footprint & Imprint locations to index by CanonicalPlace

---

footprints/templates/clientside/layer_form_template.html
media/css/pathmapper-tool.css

The layer icon on the header of the panel is, for now, a way to return to layer list. It's not the ideal location, but a temporary fix.

Temporary fix for going to layer list panel

---

media/js/app/components/mapvue.js

When the user closes the selected location panel, clear the selected marker

Pathmapper: clear the selected marker

---

footprints/templates/pathmapper/map.html

The code was previously importing a certain version (8.1) of the core highcharts and the "stable" version of heatmap, which resulted in a conflict. Pin both to a known version to prevent unexpected issues.

Pin the highcharts & heatmap versions

---

footprints/templates/search/indexes/main/actor_text.txt
footprints/templates/search/indexes/main/bookcopy_text.txt
footprints/templates/search/indexes/main/footprint_text.txt
footprints/templates/search/indexes/main/footprint_text_exact.txt
footprints/templates/search/indexes/main/imprint_text.txt
footprints/templates/search/indexes/main/person_text.txt
footprints/templates/search/indexes/main/place_text.txt
footprints/templates/search/indexes/main/writtenwork_text.txt

By default, Django templates autoescape special characters, such as apostrophes. This PR turns off autoescape when processing the search templates for Solr. Once the core is reindexed, search results should be more consistent for these corner cases.

Haystack search templates: turn off escaping 

---

footprints/main/tests/test_utils.py
footprints/main/utils.py

Though Places *should* be unique, sometimes duplicates sneak into the mix. Until we fix this hole, allow batch import to be more resilient.

Batch Import: Handle duplicate Place error

---

footprints/main/tests/test_utils.py
footprints/main/tests/test_views.py
footprints/main/utils.py
footprints/main/views.py

By default, python3 encodes to utf-8. Remove all the special handling we needed for python2 to simplify the code and ensure the proper encoding on data export.

Remove special handling for utf-8 encoding

---

footprints/pathmapper/forms.py
footprints/pathmapper/tests/test_forms.py

The start year came through as a string representing a numberic value. Handle this corner case.

Pathmapper: Handle invalid parameters

---

footprints/main/tests/test_views.py
footprints/main/views.py
footprints/templates/search/search.html

And, adjust logic to limit the full export to Footprints. Previously, the code fell through "is_valid" and resulted in an intensive iteration over the entire Solr database.

Limit full export to logged in users

---

footprints/main/views.py
footprints/templates/search/search.html

We're planning to keep a full .csv export in Academic Commons. The full exports are just too intensive for a synchronous delivery.

Limit all exports to less than 5,000 records 

---

footprints/pathmapper/forms.py
footprints/pathmapper/tests/test_forms.py

The Footprints Pathmapper feature allows users to search for book copies across a range of criteria, including footprint date ranges. In an attempt to be efficient, each of the primary Footprints Solr documents -- WrittenWork, Imprint and Bookcopy -- has a composed date range for their set of footprints and publication dates. Researchers digging into the visualization are finding this approach far too abstract. And, in many instances, the results appear incorrect or confusing.
Using the example [ʻAḳedat Yitsḥaḳ](https://footprints.ctl.columbia.edu/writtenwork/67/) with the 1522, Sefer ʻAḳedat Yitsḥaḳ  imprint: The Solr core is stocked with three documents representing the three book copies:
* 67-1945-2104,  Footprint Start: 1556-03-18, Footprint End: 1556-03-18
* 67-1945-2281. …

Pathmapper: Rethink footprint date queries

---

footprints/main/tests/factories.py

This recent CVE fix prevents pathnames in the files, causing this test
failure. https://github.com/django/django/commit/0b79eb36915d178aef5c6a7bbce71b1e76d376d3

Remove path from test file - closes #2280

---

footprints/templates/clientside/layer_list_template.html

The empty layer pane needs an empty state message. My local `footprints` is broken-ish, and I can't test `layers.length`, so, I'm hoping that works. Can you help testing it first before merging?
Thanks.

A text message for empty layer pane

---

media/css/main.css

As the carousel is constrained by width, allow the images to exist at 100% width and auto height. This should prevent distorted images.

Update carousel to favor width over height

---

footprints/templates/search/search.html

Imprint location was incorrectly used to select footprint locations in the "more" dialog.

Correct footprint location selection

---

footprints/templates/search/search.html

Adding in an image view & list view button group to prepare for work on an image gallery. These buttons are waffled at the moment.

Scaffold image gallery toggles

---

requirements.txt

Reverts ccnmtl/footprints#2989

Revert "Bump sentry-sdk from 1.32.0 to 1.33.1"

---

requirements.txt

This is the recommended way to use sentry-sdk when using the DjangoIntegration feature which we use in ctlsettings: https://docs.sentry.io/platforms/python/integrations/django/
In practice, I don't think this actually does much aside from ensuring through pip that django is installed, via the package's extras_require configuration in setup.py:
https://github.com/getsentry/sentry-python/blob/master/setup.py#L56

sentry-sdk: enable django extra

---

footprints/settings_staging.py

This is now in salt_state/apps/footprints/local_settings.py where I have RDS Proxy info set for staging.

Remove db info from settings_stage

---

footprints/templates/search/search.html

According to the template, this link is only visible under certain cases. This change fixes a sentry error with the code throws an exception.

Export button: Fix code to allow case where it doesn't exist
